on:
  push:
    paths:
      - "*.html"
      - "*.css"
      - ".github/workflows/*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set enviroment for github-release
        run: |
          echo "name=RELEASE_TAG::$(date +'%Y.%m.%d_%H.%M.%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "name=RELEASE_NAME::$TAG" >> $GITHUB_ENV
      - name: Export PDF
        run: |
          cd pdf-export
          npm install
          npm start
      - name: Create Release
        id: create_release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          files: pdf-export/cv.pdf
          gzip: false
