on: [push]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set enviroment for github-release
        run: |
          cd pdf-export
          npm install
          npm start
          export RELEASE_TAG=${RELEASE_TAG:-$(date +'%Y.%m.%d_%H.%M.%S')-$(git log --format=%h
          export RELEASE_NAME=${RELEASE_NAME:-$(date +'%Y.%m.%d_%H.%M.%S')-$(git log --format=%h
    -1)}
      - name: Create Release
        id: create_release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          files: pdf-export/cv.pdf
          gzip: false
