on: [push]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set enviroment for github-release
        run: |
          cd pdf-export
          npm install
          npm start
      - name: Create Release
        id: create_release
        uses: meeDamian/github-release@1.0
        with:
          name: ${{ $(date +'%Y.%m.%d_%H.%M.%S')-$(git log --format=%h-1) }}
          tag: ${{ $(date +'%Y.%m.%d_%H.%M.%S')-$(git log --format=%h-1) }}
          token: ${{secrets.GITHUB_TOKEN}}
          files: pdf-export/cv.pdf
          gzip: false
